import { MD3LightTheme } from 'react-native-paper';

export const theme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#3b82f6',
    primaryContainer: '#dbeafe',
    secondary: '#64748b',
    secondaryContainer: '#f1f5f9',
    tertiary: '#8b5cf6',
    tertiaryContainer: '#ede9fe',
    surface: '#ffffff',
    surfaceVariant: '#f8fafc',
    background: '#f8fafc',
    error: '#ef4444',
    errorContainer: '#fee2e2',
    onPrimary: '#ffffff',
    onPrimaryContainer: '#1e40af',
    onSecondary: '#ffffff',
    onSecondaryContainer: '#334155',
    onTertiary: '#ffffff',
    onTertiaryContainer: '#5b21b6',
    onSurface: '#0f172a',
    onSurfaceVariant: '#475569',
    onBackground: '#0f172a',
    onError: '#ffffff',
    onErrorContainer: '#991b1b',
    outline: '#e2e8f0',
    outlineVariant: '#cbd5e1',
    inverseSurface: '#1e293b',
    inverseOnSurface: '#f1f5f9',
    inversePrimary: '#93c5fd',
    shadow: '#000000',
    scrim: '#000000',
    surfaceDisabled: '#f1f5f9',
    onSurfaceDisabled: '#94a3b8',
    backdrop: 'rgba(0, 0, 0, 0.5)',
  },
  roundness: 8,
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  typography: {
    h1: {
      fontSize: 32,
      fontWeight: 'bold' as const,
      lineHeight: 40,
    },
    h2: {
      fontSize: 24,
      fontWeight: 'bold' as const,
      lineHeight: 32,
    },
    h3: {
      fontSize: 20,
      fontWeight: '600' as const,
      lineHeight: 28,
    },
    h4: {
      fontSize: 18,
      fontWeight: '600' as const,
      lineHeight: 24,
    },
    body1: {
      fontSize: 16,
      fontWeight: 'normal' as const,
      lineHeight: 24,
    },
    body2: {
      fontSize: 14,
      fontWeight: 'normal' as const,
      lineHeight: 20,
    },
    caption: {
      fontSize: 12,
      fontWeight: 'normal' as const,
      lineHeight: 16,
    },
  },
};